{% set name = "pylint-plugin-utils" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylint-plugin-utils-{{ version }}.tar.gz
  sha256: ce48bc0516ae9415dd5c752c940dfe601b18fe0f48aa249f2386adfa95a004dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - pylint >=1.7
    - python >=3.5

test:
  imports:
    - pylint_plugin_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/landscapeio/pylint-plugin-utils
  summary: Utilities and helpers for writing Pylint plugins
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anthchirp
    - jakirkham
