travis:
  secure:
    BINSTAR_TOKEN: Izz5bidIaskF/SRFZTFosc8RpbS1ZEN2H9M9fAkyev8ECnnSqW0hCUS5WRDSLO22cjHbRSRopbJP3ZVdRYX3ZDnjQlYal6tAI+m747FMtXt/dywM3H8USYxIixoidYtK0r6jboBqvURseENxHxpmb3lMODsiSx57HQnlIBq67UeXSWnq2fqYJds1bP+1p432tSXRiJQxFvEnzsx9MU0cBtcRau/9AmhNjXAh6HbbOZInYBg0IsrG3uQBavJBPkKnpIsndjRrU6LTX4V6HfCbyO6/1kOs/QvnCixqsRlV519uIHMRsVUrO9ysk7DsOmlKrIkq9LbzGUPf4pedEnsx+CHAU/eo6Qowc4jrPGzGGdU+6tcOJS8Jim7FLAHZbU6zXu9zRyemLknp3MsMNGOnOTtJH9MS4/xvWzeeM6JmBpzu0//IdeGMbN7ZNiQoDp9IpmbdJDWMeXnDwacOtxYcA7f18VFoIzLnwRa5FXpieb0FqNJRNiS3urVkRvO2h3kV0TFPG/FfKIrgml10tq9TOcmF3Q1rgV9p5XE1ssKxaVA/WpxQLg0zsM+aMpogwV76QfwpGT+Urspbs6P41K4T5HLwCyzGRCn/Y7txGQac6OiRSi7vQ26KldPlxt9dnwe84QNkS/XV0v5Cmyi9/nf+8Vyt07FXD8WfPQRrHWdUTmk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
