travis:
  secure:
    BINSTAR_TOKEN: I/1ah5ojs9A/wqyF/Y9k9ZoZ6YQLVDeXzh8z+zzVzRpyxPF0fY8V1dabJArE0Fm8aSmB04pLhglubTVu6XSnxGDW5fsjU0hXi8W95EAgv2XXDSsmGOufHQ1znKhH4eeBWdzbo8L+a++mfOlV9UUljJDi+ecRIXHvvnNQIbvp/WbfiZJCW6D2ByXgQx1QNpyKdO529f8SqtaGl3npv+PopDBRSJJ3e0s1/KGXYMF0PmYWdT6ENM2ZKHijt/2M+egPCprvEV0dViVplEW7tuv83ao2dDtpXrgUOd/NZs+KO3a7J35xwCE0lScBmTvaBbYs9ojr884ejsSH8cspbghun/0c17JERf6estuAy4KnhycEDPKcX8pIBdcj8sgQY+F34NxKKSprRihP379zzl3aAhXoun4U9vkWdFTl5rMlog4QWwlpFnaqyiY30FCHUzjCO9zVoywYSYf8IZ3EPTCGacSx2itkci9rTZ1lXfYpEJ0F3Wv6Lz/syK9kzMwhlb9ZOn/uURaNwTOyXiCzY0lS7AAjoC0A/R9oSGjnrEoAwYGjf4UfE6z8I7988YJixnXBglon4/+8zwerFGGi6FZCxsZvm6qv0zcf3urqsT5/9rO7gcFqPm72847gqTgJTNNWUHCwbXawweaamJW3qvY78OHf1i7rdr/pyqnYSBYdTIA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
