travis:
  secure:
    BINSTAR_TOKEN: aH+Jj1cxcDL2dY/QDiItRSQBxidjSTyso/Ce/VpxxByi7p9vhTvxNi66P/3yR+d1unqbvDUpiG8fm+R5V4hGDbxwPnNxySdKBkxckiWhtDKHfCqz6xIDuemdjXZRIBEB9MmOjCu804hljjGU+PpLq8hi1sEHnZ4jMAPo5dVw3s+zZ5miENPU04E2q2LNLFy3uQaS3IzGyuDMrxTEwgdj1FQuGbOACh6BUCglPXcA+aIymgvpS2CLQP7CzZqkw8/VK+V5Bk8W24F3IR/9Nd7guaPGBh7GotJTnMn5ZTtRqrKhvdkH1pMPcbcTxVRy2raHqmuGCOKHqzcPwBMJZITaPaMBf8a1ZgjCRP/Kv5Ea5WQkCW+Jd25qjnIojewfeTSkJ4mLlbJ4vY4PMXUp2Xb28lZR+rRkHvhADRsfJE3PJefYK7HPmlYkGg7YTIx4JeLOgIwn9SEWkA0zNndHIj6q+PYZY9SaiFANHj30r0OQTRgjMtUvs5U2uPYu9N6X6jBwisAm0c8FBuy2WKH2RG2TiU5xXteg4Z/QuegWqStLZtJctGa00QWhBervuWk3Bk8LQ2/umVj/S6t0WSvwbUk5uIhzygW036OVoQ0pf269Z9S5pYX8UeWIk4+dGgcqTvG2jks0CiP6j7xpOFMb6CH0GmExxQhdUlSHmLci6x4DOf8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
